nsubstitute/NSubstitute.Analyzers

src/NSubstitute.Analyzers.Shared/DiagnosticAnalyzers/AbstractNonVirtualSetupAnalyzer.cs
src/NSubstitute.Analyzers.Shared/MetadataNames.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonVirtualSetupAnalyzerTests/ThrowsAsExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonVirtualSetupAnalyzerTests/ThrowsAsExtensionMethodWithGenericTypeSpecifiedTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonVirtualSetupAnalyzerTests/ThrowsAsOrdinaryMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonVirtualSetupAnalyzerTests/ThrowsAsOrdinaryMethodWithGenericTypeSpecifiedTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonVirtualSetupAnalyzerTests/ThrowsForAnyArgsAsExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonVirtualSetupAnalyzerTests/ThrowsForAnyArgsAsExtensionMethodWithGenericTypeSpecifiedTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonVirtualSetupAnalyzerTests/ThrowsForAnyArgsAsOrdinaryMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonVirtualSetupAnalyzerTests/ThrowsForAnyArgsAsOrdinaryMethodWithGenericTypeSpecifiedTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/NonVirtualSetupAnalyzerTests/ThrowsAsExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/NonVirtualSetupAnalyzerTests/ThrowsAsOrdinaryMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/NonVirtualSetupAnalyzerTests/ThrowsAsOrdinaryMethodWithGenericTypeSpecifiedTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/NonVirtualSetupAnalyzerTests/ThrowsForAnyArgsAsExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/NonVirtualSetupAnalyzerTests/ThrowsForAnyArgsAsOrdinaryMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/NonVirtualSetupAnalyzerTests/ThrowsForAnyArgsAsOrdinaryMethodWithGenericTypeSpecifiedTests.cs

Gh 28 detect non virtual setup for throws and throwsforanyargs

---

src/NSubstitute.Analyzers.CSharp/NSubstitute.Analyzers.CSharp.csproj
src/NSubstitute.Analyzers.VisualBasic/NSubstitute.Analyzers.VisualBasic.csproj

[GH-31] - PackageIconUrl added to package definition

---

src/NSubstitute.Analyzers.Shared/DiagnosticAnalyzers/AbstractReEntrantCallFinder.cs

Gh 46 argument exception

---

ReleaseNotes.md
build/build.cake
build/releasenotes.cake
src/NSubstitute.Analyzers.CSharp/NSubstitute.Analyzers.CSharp.csproj
src/NSubstitute.Analyzers.VisualBasic/NSubstitute.Analyzers.VisualBasic.csproj

GitHub release notes

---

documentation/rules/NS1000.md
src/NSubstitute.Analyzers.Shared/DiagnosticAnalyzers/AbstractNonVirtualSetupAnalyzer.cs
src/NSubstitute.Analyzers.Shared/MetadataNames.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonVirtualSetupAnalyzerTests/ReturnsNullAsExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonVirtualSetupAnalyzerTests/ReturnsNullAsExtensionMethodWithGenericTypeSpecifiedTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonVirtualSetupAnalyzerTests/ReturnsNullAsOrdinaryMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonVirtualSetupAnalyzerTests/ReturnsNullAsOrdinaryMethodWithGenericTypeSpecifiedTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonVirtualSetupAnalyzerTests/ReturnsNullForAnyArgsAsExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonVirtualSetupAnalyzerTests/ReturnsNullForAnyArgsAsExtensionMethodWithGenericTypeSpecifiedTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonVirtualSetupAnalyzerTests/ReturnsNullForAnyArgsAsOrdinaryMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonVirtualSetupAnalyzerTests/ReturnsNullForAnyArgsAsOrdinaryMethodWithGenericTypeSpecifiedTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/NonVirtualSetupAnalyzerTests/ReturnsNullAsExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/NonVirtualSetupAnalyzerTests/ReturnsNullAsOrdinaryMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/NonVirtualSetupAnalyzerTests/ReturnsNullAsOrdinaryMethodWithGenericTypeSpecifiedTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/NonVirtualSetupAnalyzerTests/ReturnsNullForAnyArgsAsExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/NonVirtualSetupAnalyzerTests/ReturnsNullForAnyArgsAsOrdinaryMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/NonVirtualSetupAnalyzerTests/ReturnsNullForAnyArgsAsOrdinaryMethodWithGenericTypeSpecifiedTests.cs

Gh 52 non virtual call for returns null

---

src/NSubstitute.Analyzers.CSharp/DiagnosticAnalyzers/ReEntrantCallFinder.cs
src/NSubstitute.Analyzers.VisualBasic/DiagnosticAnalyzers/ReEntrantCallFinder.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/ReEntrantReturnsSetupAnalyzerTests/ReEntrantReturnsSetupDiagnosticVerifier.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/ReEntrantReturnsSetupAnalyzerTests/ReturnsAsExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/ReEntrantReturnsSetupAnalyzerTests/ReturnsAsOrdinaryMethodTests.cs
tests/NSubstitute.Analyzers.Tests.Shared/DiagnosticAnalyzers/IReEntrantReturnsSetupDiagnosticVerifier.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/ReEntrantReturnsSetupAnalyzerTests/ReEntrantReturnsSetupDiagnosticVerifier.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/ReEntrantReturnsSetupAnalyzerTests/ReturnsAsExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/ReEntrantReturnsSetupAnalyzerTests/ReturnsAsOrdinaryMethodTests.cs

[GH-71] - preventing traversing class and struct declaration when decting reentrant calls

---

src/NSubstitute.Analyzers.Shared/DiagnosticAnalyzers/AbstractNonSubstitutableMemberReceivedAnalyzer.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonSubstitutableMemberReceivedAnalyzerTests/ReceivedAsExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonSubstitutableMemberReceivedAnalyzerTests/ReceivedAsOrdinaryMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/NonSubstitutableMemberReceivedAnalyzerTests/ReceivedAsExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/NonSubstitutableMemberReceivedAnalyzerTests/ReceivedAsOrdinaryMethodTests.cs

[GH-73] - higlighting proper member when repoting NS1001

---

src/NSubstitute.Analyzers.Shared/Extensions/ISymbolExtensions.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/SubstituteAnalyzerTests/ForAsGenericMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/SubstituteAnalyzerTests/ForAsNonGenericMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/SubstituteAnalyzerTests/ForPartsOfMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/SubstituteAnalyzerTests/SubstituteDiagnosticVerifier.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/SubstituteAnalyzerTests/SubstituteFactoryCreateMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/SubstituteAnalyzerTests/SubstituteFactoryCreatePartialMethodTests.cs
tests/NSubstitute.Analyzers.Tests.Shared/DiagnosticAnalyzers/ISubstituteAnalyzerVerifier.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/SubstituteAnalyzerTests/ForAsGenericMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/SubstituteAnalyzerTests/ForAsNonGenericMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/SubstituteAnalyzerTests/ForPartsOfMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/SubstituteAnalyzerTests/SubstituteDiagnosticVerifier.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/SubstituteAnalyzerTests/SubstituteFactoryCreateMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/SubstituteAnalyzerTests/SubstituteFactoryCreatePartialMethodTests.cs

Gh-79 - recognizing InternalsVisibleTo attribute with assembly strong names

---

NSubstitute.Analyzers.sln
documentation/Compatibility.md
documentation/README.md

[GH-78] - including visual studio compatibility in documentation

---

src/NSubstitute.Analyzers.Shared/DiagnosticAnalyzers/AbstractNonSubstitutableMemberWhenAnalyzer.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonSubstitutableMemberWhenAnalyzerTests/NonSubstitutableMemberWhenDiagnosticVerifier.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonSubstitutableMemberWhenAnalyzerTests/WhenAsExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonSubstitutableMemberWhenAnalyzerTests/WhenAsOrdinaryMethodTests.cs
tests/NSubstitute.Analyzers.Tests.Shared/DiagnosticAnalyzers/INonSubstitutableMemberWhenDiagnosticVerifier.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/NonSubstitutableMemberWhenAnalyzerTests/NonSubstitutableMemberWhenDiagnosticVerifier.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/NonSubstitutableMemberWhenAnalyzerTests/WhenAsExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/NonSubstitutableMemberWhenAnalyzerTests/WhenAsOrdinaryMethodTests.cs

[GH-89] - Correctly reporting non-virtual member usage for When method calling non-virtual member from base class

---

src/NSubstitute.Analyzers.CSharp/DiagnosticAnalyzers/SubstitutionNodeFinder.cs
src/NSubstitute.Analyzers.Shared/DiagnosticAnalyzers/AbstractSubstitutionNodeFinder.cs
src/NSubstitute.Analyzers.VisualBasic/DiagnosticAnalyzers/SubstitutionNodeFinder.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonSubstitutableMemberWhenAnalyzerTests/NonSubstitutableMemberWhenDiagnosticVerifier.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonSubstitutableMemberWhenAnalyzerTests/WhenAsExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonSubstitutableMemberWhenAnalyzerTests/WhenAsOrdinaryMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/NonSubstitutableMemberWhenAnalyzerTests/NonSubstitutableMemberWhenDiagnosticVerifier.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/NonSubstitutableMemberWhenAnalyzerTests/WhenAsExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/NonSubstitutableMemberWhenAnalyzerTests/WhenAsOrdinaryMethodTests.cs

Closes #91 
@dtchepak this fixes the unfortunate 1.0.8 release

[GH-91] - better checks for when symbols usage

---

src/NSubstitute.Analyzers.CSharp/NSubstitute.Analyzers.CSharp.csproj
src/NSubstitute.Analyzers.VisualBasic/NSubstitute.Analyzers.VisualBasic.csproj

[GH-97] - Nuget metadata improvements

---

build/build.cake

Speed up appveyor build

---

src/NSubstitute.Analyzers.Shared/DiagnosticAnalyzers/AbstractCallInfoAnalyzer.cs
src/NSubstitute.Analyzers.Shared/DiagnosticAnalyzers/AbstractConflictingArgumentAssignmentsAnalyzer.cs
src/NSubstitute.Analyzers.Shared/DiagnosticAnalyzers/AbstractDiagnosticAnalyzer.cs
src/NSubstitute.Analyzers.Shared/DiagnosticAnalyzers/AbstractNonSubstitutableMemberAnalyzer.cs
src/NSubstitute.Analyzers.Shared/DiagnosticAnalyzers/AbstractNonSubstitutableMemberReceivedAnalyzer.cs
src/NSubstitute.Analyzers.Shared/DiagnosticAnalyzers/AbstractNonSubstitutableMemberWhenAnalyzer.cs
src/NSubstitute.Analyzers.Shared/DiagnosticAnalyzers/AbstractReEntrantSetupAnalyzer.cs
src/NSubstitute.Analyzers.Shared/DiagnosticAnalyzers/AbstractSubstituteAnalyzer.cs
src/NSubstitute.Analyzers.Shared/DiagnosticAnalyzers/AbstractUnusedReceivedAnalyzer.cs
tests/NSubstitute.Analyzers.Tests.CSharp/ConventionTests/AnalyzersConventionTests.cs
tests/NSubstitute.Analyzers.Tests.Shared/Fixtures/AnalyzersConventionFixture.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/ConventionTests/AnalyzersConventionTests.cs

EnableConcurrentExecution flag true by default for all analyzers

---

src/NSubstitute.Analyzers.Shared/DiagnosticAnalyzers/AbstractReEntrantCallFinder.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/ReEntrantReturnsSetupAnalyzerTests/ReEntrantReturnsSetupDiagnosticVerifier.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/ReEntrantReturnsSetupAnalyzerTests/ReturnsAsExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/ReEntrantReturnsSetupAnalyzerTests/ReturnsAsOrdinaryMethodTests.cs
tests/NSubstitute.Analyzers.Tests.Shared/DiagnosticAnalyzers/IReEntrantReturnsSetupDiagnosticVerifier.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/ReEntrantReturnsSetupAnalyzerTests/ReEntrantReturnsSetupDiagnosticVerifier.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/ReEntrantReturnsSetupAnalyzerTests/ReturnsAsExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/ReEntrantReturnsSetupAnalyzerTests/ReturnsAsOrdinaryMethodTests.cs

[GH-106] - preventing false positives for NS400 in foreach loops when element is used twice

---

appveyor.yml

Using previous ubuntu image due to breaking changes in the current one

---

NSubstitute.Analyzers.All.sln

[GH-109] - adding benchmark projects to NSubstitute.Analyzers.All solution

---

src/NSubstitute.Analyzers.CSharp/CodeFixProviders/ReEntrantSetupCodeFixProvider.cs
src/NSubstitute.Analyzers.Shared/CodeFixProviders/AbstractReEntrantSetupCodeFixProvider.cs
src/NSubstitute.Analyzers.VisualBasic/CodeFixProviders/ReEntrantSetupCodeFixProvider.cs
tests/NSubstitute.Analyzers.Tests.CSharp/CodeFixProviderTests/ReEntrantSetupCodeFixProviderTests/ReEntrantSetupCodeFixActionsTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/CodeFixProviderTests/ReEntrantSetupCodeFixProviderTests/ReEntrantSetupCodeFixVerifier.cs
tests/NSubstitute.Analyzers.Tests.CSharp/CodeFixProviderTests/ReEntrantSetupCodeFixProviderTests/ReturnsAsExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/CodeFixProviderTests/ReEntrantSetupCodeFixProviderTests/ReturnsAsOrdinaryMethodTests.cs
tests/NSubstitute.Analyzers.Tests.Shared/CodeFixProviders/IReEntrantSetupCodeFixActionsVerifier.cs
tests/NSubstitute.Analyzers.Tests.Shared/CodeFixProviders/IReEntrantSetupCodeFixProviderVerifier.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/CodeFixProvidersTests/ReEntrantSetupCodeFixProviderTests/ReEntrantSetupCodeFixActionsTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/CodeFixProvidersTests/ReEntrantSetupCodeFixProviderTests/ReEntrantSetupCodeFixVerifier.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/CodeFixProvidersTests/ReEntrantSetupCodeFixProviderTests/ReturnsAsExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/CodeFixProvidersTests/ReEntrantSetupCodeFixProviderTests/ReturnsAsOrdinaryMethodTests.cs

Closes #128 
Code fix actions for CSharp
Code fix actions for VisualBasic

GH-128 - code fix provider for NS400

---

src/NSubstitute.Analyzers.Shared/DiagnosticAnalyzers/AbstractUnusedReceivedAnalyzer.cs
src/NSubstitute.Analyzers.Shared/Extensions/SubstituteSymbolExtensions.cs
src/NSubstitute.Analyzers.Shared/MetadataNames.cs
src/NSubstitute.Analyzers.Shared/Resources.resx
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonSubstitutableMemberReceivedAnalyzerTests/ReceivedAsExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonSubstitutableMemberReceivedAnalyzerTests/ReceivedAsOrdinaryMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/UnusedReceivedAnalyzerTests/ReceivedAsExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/UnusedReceivedAnalyzerTests/ReceivedAsOrdinaryMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/NonSubstitutableMemberReceivedAnalyzerTests/ReceivedAsExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/NonSubstitutableMemberReceivedAnalyzerTests/ReceivedAsOrdinaryMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/UnusedReceivedAnalyzerTests/ReceivedAsExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/UnusedReceivedAnalyzerTests/ReceivedAsOrdinaryMethodTests.cs

Closes https://github.com/nsubstitute/NSubstitute.Analyzers/issues/131 https://github.com/nsubstitute/NSubstitute.Analyzers/issues/130

[GH-131|500] - taking into account ReceivedExtensions.Received in analyzers

---

src/NSubstitute.Analyzers.Shared/DiagnosticAnalyzers/AbstractSubstituteConstructorAnalysis.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/SubstituteAnalyzerTests/ForAsGenericMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/SubstituteAnalyzerTests/ForAsNonGenericMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/SubstituteAnalyzerTests/ForPartsOfMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/SubstituteAnalyzerTests/SubstituteDiagnosticVerifier.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/SubstituteAnalyzerTests/SubstituteFactoryCreateMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/SubstituteAnalyzerTests/SubstituteFactoryCreatePartialMethodTests.cs
tests/NSubstitute.Analyzers.Tests.Shared/DiagnosticAnalyzers/ISubstituteAnalyzerVerifier.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/SubstituteAnalyzerTests/ForAsGenericMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/SubstituteAnalyzerTests/ForAsNonGenericMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/SubstituteAnalyzerTests/ForPartsOfMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/SubstituteAnalyzerTests/SubstituteDiagnosticVerifier.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/SubstituteAnalyzerTests/SubstituteFactoryCreateMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/SubstituteAnalyzerTests/SubstituteFactoryCreatePartialMethodTests.cs

Closes https://github.com/nsubstitute/NSubstitute.Analyzers/issues/144

[GH-144] - handling protected internal constructors when analyzing NS2001 diagnostic

---

src/NSubstitute.Analyzers.CSharp/DiagnosticAnalyzers/NonSubstitutableMemberArgumentMatcherAnalyzer.cs
src/NSubstitute.Analyzers.Shared/DiagnosticAnalyzers/AbstractNonSubstitutableMemberArgumentMatcherAnalyzer.cs
src/NSubstitute.Analyzers.Shared/Extensions/IOperationExtensions.cs
src/NSubstitute.Analyzers.VisualBasic/DiagnosticAnalyzers/NonSubstitutableMemberArgumentMatcherAnalyzer.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonSubstitutableMemberArgumentMatcherAnalyzerTests/NonSubstitutableMemberArgumentMatcherDiagnosticVerifier.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonSubstitutableMemberArgumentMatcherAnalyzerTests/NonSubstitutableMemberArgumentMatcherTests.cs
tests/NSubstitute.Analyzers.Tests.Shared/DiagnosticAnalyzers/INonSubstitutableMemberArgumentMatcherDiagnosticVerifier.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/NonSubstitutableMemberArgumentMatcherAnalyzerTests/NonSubstitutableMemberArgumentMatcherDiagnosticVerifier.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/NonSubstitutableMemberArgumentMatcherAnalyzerTests/NonSubstitutableMemberArgumentMatcherTests.cs

[GH-147] - proper handling of event assignments for Arg.Any like methods

---

src/NSubstitute.Analyzers.CSharp/DiagnosticAnalyzers/CallInfoCallFinder.cs
src/NSubstitute.Analyzers.Shared/DiagnosticAnalyzers/AbstractCallInfoFinder.cs
src/NSubstitute.Analyzers.Shared/DiagnosticAnalyzers/CallInfoContext.cs
src/NSubstitute.Analyzers.Shared/DiagnosticAnalyzers/ICallInfoFinder.cs
src/NSubstitute.Analyzers.VisualBasic/DiagnosticAnalyzers/CallInfoCallFinder.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/CallInfoAnalyzerTests/AndDoesMethodPrecededByExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/CallInfoAnalyzerTests/AndDoesMethodPrecededByOrdinaryMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/CallInfoAnalyzerTests/CallInfoDiagnosticVerifier.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/CallInfoAnalyzerTests/DoMethodPrecededByExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/CallInfoAnalyzerTests/DoMethodPrecededByOrdinaryMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/CallInfoAnalyzerTests/ReturnsAsExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/CallInfoAnalyzerTests/ReturnsAsOrdinaryMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/CallInfoAnalyzerTests/ThrowsAsExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/CallInfoAnalyzerTests/ThrowsAsOrdinaryMethodTests.cs
tests/NSubstitute.Analyzers.Tests.Shared/DiagnosticAnalyzers/ICallInfoDiagnosticVerifier.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/CallInfoAnalyzerTests/AndDoesMethodPrecededByExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/CallInfoAnalyzerTests/AndDoesMethodPrecededByOrdinaryMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/CallInfoAnalyzerTests/CallInfoDiagnosticVerifier.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/CallInfoAnalyzerTests/DoMethodPrecededByExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/CallInfoAnalyzerTests/DoMethodPrecededByOrdinaryMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/CallInfoAnalyzerTests/ReturnsAsExtensionMethodsTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/CallInfoAnalyzerTests/ReturnsAsOrdinaryMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/CallInfoAnalyzerTests/ThrowsAsExtensionMethodsTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/CallInfoAnalyzerTests/ThrowsAsOrdinaryMethodsTests.cs

GH-150 - proper handling of nested calls when analyzing callinfo

---

src/NSubstitute.Analyzers.CSharp/NSubstitute.Analyzers.CSharp.csproj
src/NSubstitute.Analyzers.VisualBasic/NSubstitute.Analyzers.VisualBasic.csproj

GH-152 - marking packages as development dependencies

---

src/NSubstitute.Analyzers.Shared/DiagnosticAnalyzers/AbstractSubstituteConstructorAnalysis.cs
src/NSubstitute.Analyzers.Shared/DiagnosticAnalyzers/AbstractSubstituteConstructorMatcher.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/SubstituteAnalyzerTests/ForAsGenericMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/SubstituteAnalyzerTests/ForAsNonGenericMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/SubstituteAnalyzerTests/ForPartsOfMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/SubstituteAnalyzerTests/SubstituteDiagnosticVerifier.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/SubstituteAnalyzerTests/SubstituteFactoryCreateMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/SubstituteAnalyzerTests/SubstituteFactoryCreatePartialMethodTests.cs
tests/NSubstitute.Analyzers.Tests.Shared/DiagnosticAnalyzers/ISubstituteAnalyzerVerifier.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/SubstituteAnalyzerTests/ForAsGenericMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/SubstituteAnalyzerTests/ForAsNonGenericMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/SubstituteAnalyzerTests/ForPartsOfMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/SubstituteAnalyzerTests/SubstituteDiagnosticVerifier.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/SubstituteAnalyzerTests/SubstituteFactoryCreateMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/SubstituteAnalyzerTests/SubstituteFactoryCreatePartialMethodTests.cs

GH-162 - handling params when analyzing Substitute.For like expressions

---

src/NSubstitute.Analyzers.CSharp/CodeFixProviders/ReceivedInReceivedInOrderCodeFixProvider.cs
src/NSubstitute.Analyzers.Shared/CodeFixProviders/AbstractReceivedInReceivedInOrderCodeFixProvider.cs
src/NSubstitute.Analyzers.VisualBasic/CodeFixProviders/ReceivedInReceivedInOrderCodeFixProvider.cs
tests/NSubstitute.Analyzers.Tests.CSharp/CodeFixProviderTests/ReceivedInReceivedInOrderCodeFixProviderTests/ReceivedAsExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/CodeFixProviderTests/ReceivedInReceivedInOrderCodeFixProviderTests/ReceivedAsOrdinaryMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/CodeFixProviderTests/ReceivedInReceivedInOrderCodeFixProviderTests/ReceivedInReceivedInOrderCodeFixVerifier.cs
tests/NSubstitute.Analyzers.Tests.Shared/CodeFixProviders/IReceivedInReceivedInOrderCodeFixVerifier.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/CodeFixProvidersTests/ReceivedInReceivedInOrderCodeFixProviderTests/ReceivedAsExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/CodeFixProvidersTests/ReceivedInReceivedInOrderCodeFixProviderTests/ReceivedAsOrdinaryMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/CodeFixProvidersTests/ReceivedInReceivedInOrderCodeFixProviderTests/ReceivedInReceivedInOrderCodeFixVerifier.cs

GH-181 - code fix provider for NS5001

---

benchmarks/NSubstitute.Analyzers.Benchmarks/CSharp/CSharpDiagnosticAnalyzersBenchmarks.cs
benchmarks/NSubstitute.Analyzers.Benchmarks/VisualBasic/VisualBasicDiagnosticAnalyzersBenchmarks.cs

GH-200 - make benchmarks discoverable again

---

src/NSubstitute.Analyzers.Shared/Extensions/IOperationExtensions.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonSubstitutableMemberReceivedAnalyzerTests/NonSubstitutableMemberReceivedDiagnosticVerifier.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonSubstitutableMemberReceivedAnalyzerTests/ReceivedAsExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.CSharp/DiagnosticAnalyzerTests/NonSubstitutableMemberReceivedAnalyzerTests/ReceivedAsOrdinaryMethodTests.cs
tests/NSubstitute.Analyzers.Tests.Shared/DiagnosticAnalyzers/INonSubstitutableMemberReceivedDiagnosticVerifier.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/NonSubstitutableMemberReceivedAnalyzerTests/NonSubstitutableMemberReceivedDiagnosticVerifier.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/NonSubstitutableMemberReceivedAnalyzerTests/ReceivedAsExtensionMethodTests.cs
tests/NSubstitute.Analyzers.Tests.VisualBasic/DiagnosticAnalyzersTests/NonSubstitutableMemberReceivedAnalyzerTests/ReceivedAsOrdinaryMethodTests.cs

GH-207 - detect non virtual received checks for events subscription
